<a href="https://colab.research.google.com/github/dhanu9871/AI-ML/blob/main/lab1_20221CIT0092.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=["a","b","c","d"]
print(a)
a.append("e")
print(a)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e']


In [ ]:
list=["red","orange","pink","black"]
print(list)
list.clear()
print(list)

['red', 'orange', 'pink', 'black']
[]


In [ ]:
nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)

[1, 2, 3, 4, 1, 4, 1, 7, 8, 1]


4

In [ ]:
list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [ ]:
A=[1,2,3,4]
B=[5,6,7,8]
print(A)
print(B)
A.extend(B)
print(A)

[1, 2, 3, 4]
[5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
a=(5,)
print(a)
print(type(a))

(5,)
<class 'tuple'>


In [ ]:
a=(1,2,3,4,5)
print(a)

(1, 2, 3, 4, 5)


In [ ]:
b=(6.5,5.9,2.0)
print(b)

(6.5, 5.9, 2.0)


In [ ]:
c=("one","two","three")
c

('one', 'two', 'three')

In [ ]:
mix=("hello",708,66.8,1,2)
mix

('hello', 708, 66.8, 1, 2)

In [ ]:
a=(1,2,3,4,"hello")
print(a[4])

hello


In [ ]:
A={"name":"joy",
   "age":23,
   "education":"engineer"
   }
print(A)

{'name': 'joy', 'age': 23, 'education': 'engineer'}


In [ ]:
len(A)

3

In [ ]:
type(A)

dict

In [ ]:
x=A.keys()
print(x)

dict_keys(['name', 'age', 'education'])


In [ ]:
set1={1,2,3,4}
print(set1)

{1, 2, 3, 4}


In [ ]:
set={1,2,3,4,5,6,7,1,1}
set

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
def add():
  a=2
  b=3
  sum=a+b
  return sum
add()
print(add())

5


In [ ]:
import numpy as np

In [ ]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.size

4

In [ ]:
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.shape

(2, 3)

In [ ]:
A2.size

6

In [ ]:
A2.ndim

2

In [ ]:
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
import numpy as np

In [ ]:
z1=np.zeros(5)
print(z1)

[0. 0. 0. 0. 0.]


In [ ]:
z1.shape

(5,)

In [ ]:
z1.size

5

In [ ]:
z1.ndim

1

In [ ]:
z2=np.zeros((2,3))
print(z2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z2=np.zeros((2,3,4))
print(z2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.shape

(2, 3, 4)

In [ ]:
z2.size

24

In [ ]:
z3=np.zeros((2,3,4,5))
print(z3)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [ ]:
z3.shape

(2, 3, 4, 5)

In [ ]:
z3.size

120

In [ ]:
import numpy as np
a1=np.ones(5)
print(a1)

[1. 1. 1. 1. 1.]


In [ ]:
a2=np.ones((2,3))
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.size

6

In [ ]:
a3=np.ones((2,3,4))
print(a3)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.shape

(2, 3, 4)

In [ ]:
a3.size

24

In [ ]:
f1=np.full(5,5)
print(f1)

[5 5 5 5 5]


In [ ]:
type(f1)

numpy.ndarray

In [ ]:
f1.size

5

In [ ]:
f1.shape

(5,)

In [ ]:
f2=np.full((2,3),5)
print(f2)

[[5 5 5]
 [5 5 5]]
